# Generated by Django 2.2.4 on 2020-10-02 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text_TA3', models.CharField(max_length=200)),
                ('choice_text_DATASET', models.CharField(max_length=200)),
                ('completed', models.IntegerField(default=0)),
                ('completed_date', models.DateTimeField(verbose_name='date completed')),
                ('user_name', models.CharField(max_length=200)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Question')),
            ],
        ),
    ]
